name = "CustomVisualization"
uuid = "b5850de6-c006-4246-b88e-faf93527f37e"
authors = ["fujidana <fujidanawt@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
